# Generated by Django 3.1.4 on 2021-01-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210121_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='default', max_length=100, unique=True, verbose_name='SLUG'),
        ),
    ]
